### ISSUE TITLE
Explore API Options: Weather Data

### ISSUE THREAD

**Issue by mgallon235** [mgallon235/Kanban-working-session-30#1]

**Comment by claricemottet** [comment]
Subtasks:
- Compile list of websites that offer free API weather information.
- Evaluate each website ensuring it has weather information for the location needed and if information needs to be scraped or downloaded.
- Determine which website provides the most weather related features and whether those features are numeric or text and at what granular level the website provides weather data.
- Use website with greatest ease of use for location needed with the most numeric weather related features available and highest granularity.
